package pt.unl.fct.di.iadi.vetclinic.VetTests


import org.hamcrest.CoreMatchers.equalTo
import org.hamcrest.CoreMatchers.not
import org.junit.Assert.assertThat
import org.junit.Test
import org.junit.runner.RunWith
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.test.context.junit4.SpringRunner
import pt.unl.fct.di.iadi.vetclinic.model.*

@RunWith(SpringRunner::class)
@SpringBootTest
class VetRepoTester {

    @Autowired
    lateinit var vets: VetRepository

    companion object Constants {
        val antonio = VetDAO(-1L,"Antonio","antonio@gmail.com","tony","1234",1234, "Rua Romao", 500,mutableListOf<AppointmentDAO>(), false)
        val chenel = VetDAO(-1L,"Chenel","chenel@gmail.com","chenel","1234",1234, "Rua Romao", 501, mutableListOf<AppointmentDAO>(), false)

    }

    // IMPORTANT: the database is not cleaned between tests, it means that it will keep the pets
    // saved in previous tests

    @Test
    fun `basic test on findAll`() {
        assertThat(vets.findAll().toList(), equalTo(emptyList()))
    }

    @Test
    fun `basic test on save and delete`() {
        val vet = vets.save(antonio)
        assertThat(vet.id, not(equalTo(antonio.id)))//the id is different because it is generated by Spring
        assertThat(vet.name, equalTo(antonio.name))
        assertThat(vet.email, equalTo(antonio.email))
        assertThat(vet.username, equalTo(antonio.username))
        assertThat(vet.password, equalTo(antonio.password))
        assertThat(vet.cellphone, equalTo(antonio.cellphone))
        assertThat(vet.address, equalTo(antonio.address))
        assertThat(vet.employeeID, equalTo(antonio.employeeID))
        assertThat(vet.frozen, equalTo(antonio.frozen))

        assertThat(vets.findAll().toList(), equalTo(listOf<VetDAO>(vet)))

        vets.delete(vet);

        assertThat(vets.findAll().toList(), equalTo(emptyList()))
    }

    @Test
    fun `another test on save and delete`() {
        val vet0 = vets.save(antonio)
        assertThat(vet0.id, not(equalTo(antonio.id)))//the id is different because it is generated by Spring
        assertThat(vet0.name, equalTo(antonio.name))
        assertThat(vet0.email, equalTo(antonio.email))
        assertThat(vet0.username, equalTo(antonio.username))
        assertThat(vet0.password, equalTo(antonio.password))
        assertThat(vet0.cellphone, equalTo(antonio.cellphone))
        assertThat(vet0.address, equalTo(antonio.address))
        assertThat(vet0.employeeID, equalTo(antonio.employeeID))
        assertThat(vet0.frozen, equalTo(antonio.frozen))

        assertThat(vets.findAll().toList(), equalTo(listOf(vet0)))

        val vet1 = vets.save(chenel)
        assertThat(vet1.id, not(equalTo(chenel.id)))//the id is different because it is generated by Spring
        assertThat(vet1.name, equalTo(chenel.name))
        assertThat(vet1.email, equalTo(chenel.email))
        assertThat(vet1.username, equalTo(chenel.username))
        assertThat(vet1.password, equalTo(chenel.password))
        assertThat(vet1.cellphone, equalTo(chenel.cellphone))
        assertThat(vet1.address, equalTo(chenel.address))
        assertThat(vet1.employeeID, equalTo(chenel.employeeID))
        assertThat(vet1.frozen, equalTo(chenel.frozen))

        assertThat(vets.findAll().toList(), equalTo(listOf(vet0, vet1)))

        vets.delete(vet0)

        assertThat(vets.findAll().toList(), equalTo(listOf(vet1)))

        vets.delete(vet1)

        assertThat(vets.findAll().toList(), equalTo(emptyList()))
    }

}